# This workflow uses ServiceNow custom actions that are certified by ServiceNow.
name: CICD GitHub workflow

on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#     types: [opened, synchronize, reopened]

# env:
#   FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  
  sonarSummary:
    name: 'SonarCloud Scan Summary'
    runs-on: ubuntu-latest
    steps:
    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '20'    
    - name: ServiceNow DevOps Security Results
    # You may pin to the exact commit or the version.
    # uses: ServiceNow/servicenow-devops-security-result@26f3416768ffd3991f1a14c0304ba03075724929
      uses: ServiceNow/servicenow-devops-security-result@scratch/node20update
      with:
        # ServiceNow Instance URL
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        # Devops Integration User Name
        #devops-integration-user-name: # optional
        # Devops Integration User Password
        #devops-integration-user-password: # optional
        # Devops Integration Token
        devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }} # optional
        # Github Context
        context-github: ${{ toJSON(github) }}
        # Display Name of the Job
        job-name: 'Veracode Scan Summary'
        # Security Results Attributes: For more information on defining the security attributes, View full Marketplace listing link above
        security-result-attributes: '{ "scanner": "Veracode", "applicationName": "10kflaws-72", "securityToolId": "" }'
        # Orchestration Tool Id
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      
    env:
        #if: github.event.pull_request.merged == true
        name: Deploy
        environment: PROD
        needs: sonarSummary
        runs-on: ubuntu-latest
      
