name: Test

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build

  SecurityScanResults:
    needs: build
    runs-on: ubuntu-latest
    name: Servicenow Security Scan Results

    steps:
       - name: ServiceNow DevOps Security Results23
         uses: maheshganji/custom-action-get@sonar
         with:
            devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
#             devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
            devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            context-github: ${{ toJSON(github) }}
            job-name: 'Servicenow Security Scan Results'
            security-result-attributes: '{"scanner": "Veracode", "applicationName": "Azure", "buildVersion": "v1"}'
# {"applicationName": "Azure", "buildVersion": "v1"}
