# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: Github Sonar and Security Demo
on: workflow_dispatch

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile

  sonarScan:
    name: 'Sonar Scan'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0

    - name: ServiceNow DevOps Sonar Scan Results
      uses: ServiceNow/servicenow-devops-sonar@dev
      with:
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        context-github: ${{ toJSON(github) }}
        job-name: 'Sonar Scan'
        sonar-host-url: ${{ secrets.SONAR_URL }}
        sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}

  # wait:
  #   name: 'Wait for 2 Minutes'
  #   needs: sonarScan
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Sleep for 2 minutes
  #     run: sleep 120
