name: Test

on:
  workflow_dispatch:    
jobs:
  Stage_1:
    runs-on: ubuntu-latest
    steps:
    - name: Job 1
      run: echo "Running Job 1"
  Stage_2:
    runs-on: ubuntu-latest
    needs: Stage_1
    steps:
      - name: Job 2
        run: echo "Running Job 2"
  Stage_3:
    runs-on: ubuntu-latest
    needs: Stage_2
    steps:
      - name: Job 3
        run: echo "Running Job 3"
  Stage_4:
    runs-on: ubuntu-latest
    needs: Stage_3
    steps:
      - name: Job 4
        run: echo "Running Job 4"
  Stage_5:
    runs-on: ubuntu-latest
    needs: Stage_4
    steps:
      - name: Job 5
        run: echo "Running Job 5"
